# Generated by Django 5.0.6 on 2024-06-21 21:09

import django.contrib.postgres.fields
import django.db.models.deletion
import media.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('channel_name', models.CharField(max_length=50)),
                ('channel_description', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.channel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=500)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('genera', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GEN', 'GENERAL'), ('TECH', 'TECHNOLOGY'), ('LEARN', 'LEARNING_TEACHING'), ('ENT', 'ENTERTAINMENT'), ('ANI', 'ANIME'), ('MU', 'SONGS_MUSIC'), ('MOV', 'MOVIES'), ('MED', 'MEDICAL')], max_length=20), default=media.constants.get_genera, size=None)),
                ('search_string', models.TextField(default='')),
                ('channel_id', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='media.channel')),
                ('playlist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='user.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_like', to='media.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('comment_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='media.video')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comment', to='media.video')),
            ],
        ),
    ]
