# Generated by Django 5.0.6 on 2024-06-26 14:54

import django.contrib.postgres.fields
import django.db.models.deletion
import media.constants
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('channel_name', models.CharField(max_length=50)),
                ('channel_description', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.channel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3d491a3d-0ac3-43c4-b0e2-3beb40306acb'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=500)),
                ('thumbnail_extension', models.CharField(max_length=10)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('genra', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GEN', 'GENERAL'), ('TECH', 'TECHNOLOGY'), ('LEARN', 'LEARNING_TEACHING'), ('ENT', 'ENTERTAINMENT'), ('ANI', 'ANIME'), ('MU', 'SONGS_MUSIC'), ('MOV', 'MOVIES'), ('MED', 'MEDICAL')], max_length=20), default=media.constants.get_default_genra, size=None)),
                ('hash_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('search_string', models.TextField(default='')),
                ('available_quality', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=5), default=list, size=None)),
                ('upload_status', models.CharField(choices=[('PEND', 'PENDING'), ('APR', 'APPROVED'), ('ERR', 'ERROR')], default='PEND', max_length=4)),
                ('channel_id', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='media.channel')),
                ('playlist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='user.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_like', to='media.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('comment_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='media.video')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comment', to='media.video')),
            ],
        ),
    ]
