# Generated by Django 5.0.6 on 2024-06-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='customer',
            new_name='user',
        ),
    ]
