# Generated by Django 5.0.6 on 2024-06-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
