# Generated by Django 5.0.6 on 2024-06-22 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_video_thumbnail_alter_video_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playlist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.playlist'),
        ),
    ]
