# Generated by Django 5.0.6 on 2024-06-20 13:36

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_customer_video_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genera',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GEN', 'GENERAL'), ('TECH', 'TECHNOLOGY'), ('LEARN', 'LEARNING_TEACHING'), ('ENT', 'ENTERTAINMENT'), ('ANI', 'ANIME'), ('MU', 'SONGS_MUSIC'), ('MOV', 'MOVIES'), ('MED', 'MEDICAL')], max_length=20), default=['GEN'], size=None),
        ),
        migrations.AddField(
            model_name='video',
            name='search_string',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('comment_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='media.video')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comment', to='media.video')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='user.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_like', to='media.video')),
            ],
        ),
    ]
