# Generated by Django 5.0.6 on 2024-07-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_thumbnail',
            field=models.CharField(default='-', max_length=1000),
        ),
        migrations.AddField(
            model_name='channel',
            name='extension',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
