# Generated by Django 5.0.6 on 2024-07-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_channel_channel_thumbnail_channel_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_extension',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
