# Generated by Django 5.0.6 on 2024-06-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_video_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload_status',
            field=models.CharField(choices=[('PEND', 'PENDING'), ('APR', 'APPROVED'), ('ERR', 'ERROR')], default='PEND', max_length=4),
        ),
    ]
