# Generated by Django 5.0.6 on 2024-06-20 13:43

import django.contrib.postgres.fields
import media.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_video_genera_video_search_string_video_uploaded_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genera',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GEN', 'GENERAL'), ('TECH', 'TECHNOLOGY'), ('LEARN', 'LEARNING_TEACHING'), ('ENT', 'ENTERTAINMENT'), ('ANI', 'ANIME'), ('MU', 'SONGS_MUSIC'), ('MOV', 'MOVIES'), ('MED', 'MEDICAL')], max_length=20), default=media.constants.get_genera, size=None),
        ),
    ]
