# Generated by Django 5.0.6 on 2024-06-25 19:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_rename_genera_video_genra_video_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='available_quality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=5), default=[], size=None),
        ),
        migrations.AddField(
            model_name='video',
            name='hash_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
    ]
