# Generated by Django 5.0.6 on 2024-06-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
